/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AttendanceRouteImport } from './routes/attendance'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as SimulatorRouteImport } from './routes/simulator'
import { Route as ApiAdvisorRouteImport } from './routes/api/advisor'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendanceRoute = AttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulatorRoute = SimulatorRouteImport.update({
  id: '/simulator',
  path: '/simulator',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdvisorRoute = ApiAdvisorRouteImport.update({
  id: '/api/advisor',
  path: '/api/advisor',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/attendance': typeof AttendanceRoute
  '/dashboard': typeof DashboardRoute
  '/simulator': typeof SimulatorRoute
  '/api/advisor': typeof ApiAdvisorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/attendance': typeof AttendanceRoute
  '/dashboard': typeof DashboardRoute
  '/simulator': typeof SimulatorRoute
  '/api/advisor': typeof ApiAdvisorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/attendance': typeof AttendanceRoute
  '/dashboard': typeof DashboardRoute
  '/simulator': typeof SimulatorRoute
  '/api/advisor': typeof ApiAdvisorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/attendance' | '/dashboard' | '/simulator' | '/api/advisor'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/attendance' | '/dashboard' | '/simulator' | '/api/advisor'
  id:
    | '__root__'
    | '/'
    | '/attendance'
    | '/dashboard'
    | '/simulator'
    | '/api/advisor'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AttendanceRoute: typeof AttendanceRoute
  DashboardRoute: typeof DashboardRoute
  SimulatorRoute: typeof SimulatorRoute
  ApiAdvisorRoute: typeof ApiAdvisorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendance': {
      id: '/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulator': {
      id: '/simulator'
      path: '/simulator'
      fullPath: '/simulator'
      preLoaderRoute: typeof SimulatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/advisor': {
      id: '/api/advisor'
      path: '/api/advisor'
      fullPath: '/api/advisor'
      preLoaderRoute: typeof ApiAdvisorRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AttendanceRoute: AttendanceRoute,
  DashboardRoute: DashboardRoute,
  SimulatorRoute: SimulatorRoute,
  ApiAdvisorRoute: ApiAdvisorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
